### ISSUE TITLE
backup minecraft server

### ISSUE THREAD

**Issue by audy** [nukep/Dockerfiles#1]
Do you have any ideas for how to back up the server while it is running? I've seen scripts to do this that interact with the server via screen but I have yet to see a solution that works with Docker+minecraft.

**Comment by audy** [comment]
I'm back!

Here is a little hack I came up with using the Ruby docker-api Gem:

``` ruby
require 'docker'

container = Docker::Container.get('distracted_pasteur')

def s container, cmd
  puts cmd
  container.attach(stdin: StringIO.new("#{cmd}\n"))
end

s container, '/say SERVER BACKUP STARTING. HUG THE NEAREST OBJECT.'

# stop saving
s container, '/save-off'

# copy world
`cp -r falafel falafel.bak`

# start saving again
s container, '/save-on'

s container, '/say SERVER BACKUP COMPLETE. THANK YOU.'
```

**Comment by nukep** [comment]
Nice!

I'm a fan of scripts like these that remote into Docker containers, as opposed to embedding `cron` jobs into them. It's a clear separation of concerns that works.

What we could do is add a "Backup" section in the README that links to your script. Maybe even link to a mini-guide here on the repo that tells people how to set up `cron` with it.

Let me know if you're up to sending a pull request.

**Comment by audy** [comment]
Sure,

I can post my script a Gist and link to it in the readme.
